version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smartID
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - 8081:8080